README.md
Added the projects that we'll be doing during the Global Sprint so that participants will know what kinds of contributions people might make to the project(s).
=> update README with Global Sprint info

CONTRIBUTING.md, README.md
Added CONTRIBUTING.md
Updated README with link to Mozilla Community Participation Guidelines
Updated README with clearer information about time/location of our Global Sprint
=> CONTRIBUTING.md and Global Sprint details

README.md
Added a link to the CONTRIBUTING.md in the README.md
=> Link to CONTRIBUTING.md in README.md

resbaz/resbazTucson2021.md
Colors updated! but part of the iframe was cut off, so hopefully this is enough wiggle room so we can read it all.
=> make iframe longer and scrollable

.gitignore, _data/en.yml, _includes/header.html, resbaz/resbazTucson2022.md
(Also remove shut up and write logo)
=> Add 2022 stub page

resbaz/resbazTucson2022.md
Looks like this for now; see the "Files changed" tab for exactly what's different:
=> Add tentative embedded calendar and update sponsors

resbaz/resbazTucson2022.md
Add logo for UA Libraries to 2022 sponsors section.
=> Add Libraries to sponsor list

resbaz/resbazTucson2022.md
Change from form-editing link to form-filling link
=> Update Google Form registration link

_data/members.yml
YAML file might not like markdown formatting of links, so trying members page without it...
=> Update membership 2022

_data/members.yml
=> Update J Guo's bio

CONTRIBUTING.md, README.md
Just fixing some spelling errors
=> spellcheck

_data/members.yml
Add bio for Chris Reidy to _data/members.yml
=> Add C. Reidy bio

_includes/header.html, resbaz/resbazTucson2023.md
Updates the navbar to point to a new 2023 festival page
=> Festival 2023

_config.yml, _includes/css/agency.css, resbaz/Arizona2023.md
For anyone unable / not feeling like going through the `jekyll serve` rigamarole to see what this looks like locally, here are some screenshots:
=> Add tabs with maps to each festival location

.gitignore, _quarto.yml, resbaz/resbazTucson2024.qmd
Feel free to commit directly to this branch!
Fixes #78 
Nothing will be live until this PR is merged.
=> Add stub page for resbaz 2024

.devcontainer/devcontainer.json
This will allow editing in VS Code with live preview using Quarto CLI.
=> Add configuration for GitHub Codespaces

resbaz/resbazTucson2024.qmd
Before we merge this, please double-check that the auto-generated email links do what you'd expect!
(I'm not totally sure they'll always do sensible things with different OSes / email clients / etc)
I may keep this branch open to replace the google sheet with a proper Observable calendar at some point...
=> Add placeholder google sheet calendar with pre-populated email links

resbaz/resbazTucson2024.qmd
I tried to set some expectations here.
=> Added more information about the unconference

index.qmd, resbaz/resbazTucson2024.qmd
remove registration link, add to previous events log
=> archive 2024 festival

_quarto.yml, index.qmd
Closes #102.
What do y'all think?  I like this better.
=> use navbar dropdown for previous festival pages

_quarto.yml, resbaz/resbazTucson2025.qmd
Fixes #107 
Some open questions, so leaving this as a draft for now.
@julianpistorius, the build / deploy thing seems to be failing because the `ORGANIZATION_READER` token has gone bad... not sure if it's expired, or if we (or github) changed something. I don't think I can access resbazaz tokens (no settings menu visible for me)... could you take a look?
=> Add 2025 festival page

resbaz/resbazTucson2025.qmd
Update the 2025 page with registration link. Also updated the room from TBD to Catalyst Studios and fixed the map link.  If the registration is not meant to be open yet, feel free not to merge.
=> Add registration link and room

index.qmd, resbaz/resbazTucson2025.qmd
=> add schedule
